import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {AuthProvider} from "@lib/auth";
import {Navbar} from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
      <link
        rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
        crossOrigin="anonymous"
      />
    </head>
    <body className={inter.className}>
      <AuthProvider>
        <Navbar />
        <div className="container">
          {children}
        </div>
      </AuthProvider>
    </body>
    </html>
  );
}
